FROM python:3.12-alpine

WORKDIR /app

RUN apk add uv --no-cache

COPY pyproject.toml .
COPY uv.lock .

RUN uv sync --no-dev --frozen

ENV UV_NO_SYNC=1

COPY config/ ./config/
COPY mcp_server.py .
COPY modules/ ./modules/
COPY type_definitions/ ./type_definitions/


ENV QDRANT_URL=http://qdrant:6333
ENV EMBEDDING_BASE_URL=http://ollama-embeddings:11434

CMD ["uv", "run", "fastmcp", "run", "mcp_server.py:mcp", "--transport", "http", "--port", "8000", "--host", "0.0.0.0"]

EXPOSE 8000

STOPSIGNAL SIGKILL
